version: '3'
services:
    plex:
        image: plexinc/pms-docker:latest
        restart: unless-stopped
        ports:
            - 32400:32400/tcp
            - 3005:3005/tcp
            - 8324:8324/tcp
            - 32469:32469/tcp
            - 1900:1900/udp
            - 32410:32410/udp
            - 32412:32412/udp
            - 32413:32413/udp
            - 32414:32414/udp
        environment:
            - TZ=America/New_York
            - PLEX_CLAIM=claim-NLmHz7nqdsLbzbbYc59E
            - ADVERTISE_IP=http://192.168.1.41:32400/
        hostname: plex
        volumes:
            - plex-config:/config
            - /mnt/data/plex/plex_data/media:/data
    deluged:
        image: cvittoria/deluged:latest
        restart: unless-stopped
        depends_on:
            - vpn-client
        network_mode: "service:vpn-client"
        environment:
            - PUID=1001
            - PGID=1001
            - TZ=America/New_York
        volumes:
            - /mnt/data/misc:/downloads
            - /mnt/data/plex/plex_data/media:/downloads/media
            - deluge:/config
        #command: deluge-console -c /config config --set allow_remote true
    vpn-client:
        image: dperson/openvpn-client
        cap_add:
            - net_admin
        security_opt:
            - label:disable
        environment:
            - TZ=America/New_York
            - DNS=10.0.254.1
        restart: unless-stopped
        volumes:
            - /mnt/data/openvpn/config:/vpn
    deluge-web:
       image: cvittoria/deluge-web:latest
       depends_on:
            - deluged
       environment:
            - TZ=America/New_York
       ports:
            - 8112:8112/tcp
       restart: unless-stopped
       links:
            - vpn-client:deluged
       volumes:
            - delugew-config:/config

volumes:
    plex-config:
    deluge:
    delugew-config:

networks:
    internal: